export const CREATE_PRESCRIPTION = "CREATE_PRESCRIPTION";
export const FETCH_PRESCRIPTIONS = "FETCH_PRESCRIPTIONS";
export const FETCH_PRESCRIPTION = "FETCH_PRESCRIPTION";
export const EDIT_PRESCRIPTION = "EDIT_PRESCRIPTION";
export const DELETE_PRESCRIPTION = "DELETE_PRESCRIPTION";